/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.kamsoft.api.App;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        App classUnderTest = new App();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertTrue(true);
    }
}
